version: "3"
services:
    server:
        container_name: server-container
        build: ./server
        ports:
            - "5000:5000"
        depends_on: 
            - mongo

    client:
        container_name: client-container
        build: ./client
        ports:
            - "3000:3000"
        depends_on: 
            - server
    
    mongo:
        container_name: mongo-database
        image: mongo        
        environment:
            - MONGO_INITDB_ROOT_USERNAME=danyu
            - MONGO_INITDB_ROOT_PASSWORD=password
        expose: 
            - "27017"
        volumes: 
            - serverDB:/data/db

volumes: 
    serverDB:
