version: "3"
services:
    server:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - PORT=5000
